commit-msg hook workaround for ask-cli issue ask init seems to fail if the current folder has a git repo So using an empty temp subdirectory works

diff --git a/code/hooks/commit-msg b/code/hooks/commit-msg
--- a/code/hooks/commit-msg
+++ b/code/hooks/commit-msg
@@ -29,8 +29,29 @@ then
 		skillId=$(tr -d '\n' < "./$SRC_FOLDER/index.ts"| tr -d ' ' | sed -n 's/.*withSkillId\(.*\)/\1/p' | cut -f1 -d ")" | tr -d "()\"'")
 		if [ -n "$skillId" ]
 		then
+			# Workaround for ask-cli issue: using a temp folder
+			# (ask init fails if current folder has a git repo)
+			starting_dir="$(pwd)"
+			tmp_dir="$BUILD_FOLDER-tmp"
+			mkdir "$tmp_dir"
+			cd "$tmp_dir"
+
+			# Run the ask init command and store the status code
 			echo "$BUILD_FOLDER" | ask init --hosted-skill-id "$skillId"
-			[ $? -ne 0 ] && exit 1 # If the ask init command failed, exit with an error
+			ask_init_status_code=$?
+			
+			cd "$starting_dir"
+
+			if [ $ask_init_status_code -eq 0 ]
+			then
+				# Move the build repo back to the original folder
+				mv "$tmp_dir/$BUILD_FOLDER" .
+				# Remove the temp folder
+				rm -rf "$tmp_dir"				
+			else
+				# If the ask init command failed, exit with an error
+				exit 1
+			fi
 		else
 			echo "Error: The $BUILD_FOLDER folder does not exist, and the skill id could not be obtained."
 			echo "Please, look up the skill id for this skill and run the following command in the root folder:"
